apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: spyss-frontend
  name: spyss-frontend
  namespace: spyss-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spyss-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spyss-frontend
    spec:
      containers:
      - image: gcr.io/spidercal-31101988/spyss-frontend:latest
        imagePullPolicy: IfNotPresent
        name: spyss-frontend
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
