  
apiVersion: v1
kind: Service
metadata:
  name: spyss-frontend-service
  namespace: spyss-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: spyss-frontend
